### PR TITLE
add: hoist-import-deps

### PR DESCRIPTION
**Pull request by vikerman**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/rollup/awesome/blob/master/.github/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Provide a Link A Repository for Your Addition

https://github.com/vikerman/rollup-plugin-hoist-import-deps

### Please Describe Your Addition

When a module is dynamically imported, it's static imports in turn are loaded after the dynamic import is downloaded and parsed. This causes a delay when doing dynamic imports especially with slow/high latency connections. This plugin changes the dynamic import call site to also add(hoist) the static imports of the module being loaded so that the dynamically imported module and it's dependencies are loaded in parallel instead of in two steps.

### CODE REVIEW

**Comment by shellscape** [comment]
If you read the guidelines, you'd know why this is being closed.

**Comment by vikerman** [comment]
Sorry. I'm not sure. Thanks for your time.

**Comment by shellscape** [comment]
It's literally the very first bullet point:

> If you just created something, wait at least 30 days before submitting. This is to give it some time to mature and ensure it's not just a publish-and-forget type of project.

**Comment by vikerman** [comment]
Once again - I'm sincerely sorry if I'm being dumb. Definitely not trying to be malicious.

First version published on May 18th(>30 days) (And have been fixing issues since then and felt good about the current state)

I thought that was sufficient for satisfying the first point.

**Comment by shellscape** [comment]
Welp. This one is my fault. I'm not sure why, but the second page of commits on your repo was not available when I first looked at it. It appeared as if your project was only 27 days old.

The apology is owed by me. My apologies.

**Comment by vikerman** [comment]
Phew - Thanks. Glad that's sorted. Please let me know if I should adjust anything else.

**Comment by vikerman** [comment]
Hi - Please let me know if anything else needs to be done from my side here. Thanks.

**Comment by shellscape** [comment]
thanks!

**Pull request merged**
