### PR TITLE
Add rollup-plugin-copier

### PR DESCRIPTION
**Pull request by marverix**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/rollup/awesome/blob/master/.github/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

I'm adding rollup-plugin-copier which is simple plugin that copies desired files during specified phase (it's configurable).

### CODE REVIEW

**Comment by shellscape** [comment]
Thank you for the PR. Can you please highlight how this plugin differs and/or is better in any way(s) to https://github.com/meuter/rollup-plugin-copy?

**Comment by marverix** [comment]
I don't see this in https://github.com/rollup/awesome/blob/master/.github/CONTRIBUTING.md . So why are you asking? Have you asked authors of `copy-assets` and `cpy` the same question?

**Comment by marverix** [comment]
`rollup-plugin-copy`:
* last merge 2 years ago
* it's not working with new Rollup (wrong hook)

`rollup-plugin-copier`:
* working with new Rollup
* configurable hook
* can create target directory if does not exist

**Comment by vladshcherbin** [comment]
Hey, I'm the new maintainer of `rollup-plugin-copy`, just saw this issue.

None of above is true in new versions of `rollup-plugin-copy`:

`0.3.0` - support for new rollup api
`1.0.0` - fully rewritten with new features (create directories if needed, has multiple destinations, etc) and 100% test coverage
`2.0.0` - option to set hook

A lot of duplicate packages were created when `rollup-plugin-copy` was not maintained, but it's not a problem now 😉

**Comment by marverix** [comment]
This is totally unfair. I created this PR before. I will not comment "2.0.0 - option to set hook" as for me it sounds like you copied that function from me. Oh irony.

**Comment by vladshcherbin** [comment]
@marverix sure, copied your function, really? I added it because it was asked in one of `rollup-plugin-copy` issues and was a conclusion from a pr there.

Instead of creating a new duplicate package, polluting npm and spamming your package in all `rollup-plugin-copy` issues you could ask to transfer that package and maintain it instead which is what I did. 

With all respect, I'd suggest you deprecate your package since it doesn't add any benefit over `rollup-plugin-copy` and is just a duplicate for no reason.

**Comment by marverix** [comment]
> Instead of creating a new duplicate package, polluting npm and spamming your package in all rollup-plugin-copy issues you could ask to transfer that package and maintain it instead which is what I did.

I want to remind you that author of that repo didn't respond nor merge anything for 2 years. So it's clear that if someone is not answerin for such long period of time then it's madness to wait until one will give you ownership. Sure I'm happy that it turned it way, but I will not depracate my repo. 

Please don't spam anymore in this issue. Thank you.

**Comment by vladshcherbin** [comment]
@marverix you didn't even try. Somehow I managed to get all work done in a week. 🤷‍♂️

Of course you won't deprecate, duplicated package for no reason is a great addition to npm and rollup community. Same thing for already 10 or more similar copy packages, over and over again. Imagine all of them add a PR here 🤔👍

**Comment by marverix** [comment]
OMG, which word of "Pleast don't spam anymore" you didn't understand?...

**Comment by shellscape** [comment]
Folks, this is not the forum to debate the merits of one plugin over another - this list is not a competition. Submissions are vetted by maintainers to ensure that quality is maintained _for the users_. Delay of a submission is not an insult. Patience is a virtue.

**Pull request closed without merging**
