### PR TITLE
Add deno-rollup

### PR DESCRIPTION
**Pull request by cmorten**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/rollup/awesome/blob/master/.github/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Provide a Link A Repository for Your Addition

<https://github.com/cmorten/deno-rollup>

### Please Describe Your Addition

`deno-rollup` ports Rollup so it can be used within Deno scripts to bundle modules.

render1613311890881

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the PR. One question - is this a fork (or contain source copies/modifications) or a wrapper of Rollup?

**Comment by cmorten** [comment]
This is a wrapper of the Rollup browser export which is then fleshed out to provide the same ( / as similar as can reasonably achieve ) JavaScript API and CLI.

In order to fill in parts of the interface that are not included in the browser export, there have been some source copies / modifications included in the module.

**Comment by shellscape** [comment]
> In order to fill in parts of the interface that are not included in the browser export, there have been some source copies / modifications included in the module.

No worries. I would like to see a copy of Rollup's license in the repo given that there are copies and mods of original source in there. (It's the right thing to do)

**Comment by cmorten** [comment]
@shellscape I very much agree, not only as the right thing to do, but also the requirement under MIT licensing - which is which the license has been present in the repo from the initial commit, available in the root under https://github.com/cmorten/deno-rollup/blob/main/ROLLUP_LICENSE.md, referenced in the README.md in the license section ( REF: https://github.com/cmorten/deno-rollup/#license ) and I have endeavoured to also link back specific files to their "original" counterparts so it is apparent in the source code what is a derived work versus new 😄 

Please advise if you are expecting more than this with regards to licensing?

**Comment by shellscape** [comment]
Totally missed that, my fault there. I went straight to LICENSE. I'm perhaps too used to seeing multiple licenses packed into that file.

**Comment by shellscape** [comment]
thanks!

**Pull request merged**
