### PR TITLE
Add `lit-html`

### PR DESCRIPTION
**Pull request by rockerest**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/rollup/awesome/blob/master/.github/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### rollup-plugin-lit-html

This addition lists `lit-html` as one of the options in the templating section. I chose this section because I think it fits better than others, but arguments could be made that `lit-html` is not strictly a templating library, and this plugin modifies the code output so that the HTML is converted into a template function for use with other `lit-html` tooling (like `render`) or `lit-element`.

I'm happy to move the category this is in, but I think most people will perceive `lit-html` as being a templating tool.

As implied by the name, `rollup-plugin-lit-html` allows an application to separate their `lit-html` template (essentially just raw HTML with template string interpolation) from the rest of their JavaScript. It's not for everyone, as many people like mixing the two, but for those who like to separate their JS and their HTML, it's a non-trivial task to extract the HTML from the JS when you use `lit-html`.

I think this is very useful for those people, and there's nothing like it out there that I've found, and certainly nothing like it on this list.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for the submission.

Seems you've found a peculiar grey-area in our Contributing Guidelines. While your repo is over 30 days old, you only just published this for public consumption [an hour or so ago](https://www.npmjs.com/package/rollup-plugin-lit-html). We're going to have to let this one brew for a while longer to let folks try it out and to let it mature some before adding it.

**Comment by rockerest** [comment]
Happy to wait since the package namespace is new, but it's actually been published under a different name for it's entire life: https://www.npmjs.com/package/rollup-plugin-bundle-lit-html

**Comment by shellscape** [comment]
Ah! Pertinent information!

**Comment by rockerest** [comment]
Yep sorry about that.

I didn't realize the NPM publish status was the 30 day bake-in :D

**Comment by shellscape** [comment]
Cheers 🍻

**Pull request merged**
