### PR TITLE
add: robins-rollup-plugin-eslint

### PR DESCRIPTION
**Pull request by robinloeffel**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/rollup/awesome/blob/master/.github/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Provide a Link A Repository for Your Addition

https://github.com/robinloeffel/rollup-plugin-eslint

### Please Describe Your Addition

This plugin allows you to use the most recent version of ESLint with Rollup. I am aware that there already is a plugin called [`rollup-plugin-eslint`](https://github.com/TrySound/rollup-plugin-eslint), but it doesn't work with ESLint@7.

I originally intended for the plugin to be called `@robinloeffel/rollup-plugin-eslint`, but as I noticed you can't just publish a scoped package on the free tier. Because of that, it's called `robins-rollup-plugin-eslint`, which I'm not really a fan of, to be honest. So I'd be really open for any advice you (@rollup) or anyone would have.

### CODE REVIEW

**Comment by shellscape** [comment]
> If you just created something, wait at least 30 days before submitting. This is to give it some time to mature and ensure it's not just a publish-and-forget type of project.

You checked the box that you read the guidelines twice. Not cool. 

You can publish scoped on the free tier. Look up `publishConfig`

**Comment by robinloeffel** [comment]
I did, yes. I'd been working on it since before I've put on GitHub. If you check the [init commit](https://github.com/robinloeffel/rollup-plugin-eslint/commit/af170ef60559873c692415ba7148a655a3062aa0), you'll see that everything is already there and ready. I realize now that of course there is no way for you to verify that.

I'll have a look `publishConfig`, thanks for the heads-up!

**Comment by shellscape** [comment]
Do we need better verbiage on that point to specify that something needs to be in the wild and usable by others?

**Comment by robinloeffel** [comment]
Well I guess most people will understand it, so no, not really. 😄

**Pull request closed without merging**
