### PR TITLE
Add rollup-plugin-imagemin

### PR DESCRIPTION
**Pull request by malchata**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/rollup/awesome/blob/master/.github/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Describe Your Addition

`rollup-plugin-imagemin` uses imagemin to optimize image assets. It functions like most any other abstraction of imagemin, and offers many of the same features.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for submitting your plugin. What's the backstory behind the following line from your README?

> rollup-plugin-imagemin is not production-ready!

**Comment by malchata** [comment]
Ah, that. It was a leftover from before I wrote tests for the plugin. Barring any bugs that would be discovered in due time, I'm reasonably confident it will work. I can strike that from the readme if need be.

Also, sorry for the weird title. Not sure why I put "rollup-plugin-smart-asset" instead of "rollup-plugin-imagemin".

**Comment by malchata** [comment]
I updated my package README to remove the "not production ready" warning. Let me know if you see any other issues.

**Comment by shellscape** [comment]
Thanks for that. Sorry I didn't get back to you earlier yesterday, had a bit of a rough day there. Looks good to merge.

**Comment by malchata** [comment]
It's all good! We all have our lives to live. 😊

Thanks for merging this. I really appreciate it!

**Pull request merged**
