### PR TITLE
add: @rbnlffl/rollup-plugin-eslint

### PR DESCRIPTION
**Pull request by robinloeffel**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/rollup/awesome/blob/master/.github/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Provide a Link A Repository for Your Addition

https://github.com/robinloeffel/rollup-plugin-eslint

### Please Describe Your Addition

See https://github.com/rollup/awesome/pull/66 – and sorry for the inconveniece! In the meantime, I've released the package under `@rbnlffl/rollup-plugin-eslint`. The reason for this plugin to exist is still the same: The most popular integration between rollup and ESLint, [`rollup-plugin-eslint`](https://github.com/TrySound/rollup-plugin-eslint), hasn't been touched in over a year now and references `eslint@^6.0.0`, resolving to `v6.8.0`, thus preventing you from using newer features.

### CODE REVIEW

**Comment by shellscape** [comment]
@TrySound would you be interested in a PR to update the plugin? I'd like to avoid duplicate plugins in the list if at all possible, but @robinloeffel does have a good point that it's very out of date.

**Comment by TrySound** [comment]
Oh, right. I forgot about this plugin. Will look into it.

**Comment by robinloeffel** [comment]
Any updates?

**Comment by TrySound** [comment]
https://github.com/rollup/plugins/pull/575

**Pull request closed without merging**
