### PR TITLE
add rollup-plugin-banner

### PR DESCRIPTION
**Pull request by yingye**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/rollup/awesome/blob/master/.github/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Describe Your Addition

add rollup-plugin-banner

### CODE REVIEW

**Comment by shellscape** [comment]
I'm sorry, but we can't accept your submission at this time. From the contributing guidelines:

> If you just created something, wait at least 30 days before submitting. This is to give it some time to mature and ensure it's not just a publish-and-forget type of project.

Unfortunately, your project is only 5 days old. Your project also lacks documentation on how this differ's from the built-in Rollup banner functionality, which could be confusing to users and misunderstood as duplicating the same function. I would suggest adding documentation to clear that up and clearly state the differences.

Please re-apply for addition to the list after your project is 30 days old, or ping us on this PR and we'll revisit it.

**Comment by yingye** [comment]
@shellscape 30 days passed :smile:

**Comment by GrosSacASac** [comment]
Not sure, but maybe this should solved by changing rollup core:

**Append banner after all plugins**

**Comment by shellscape** [comment]
@lukastaegert is this something that core does/provides in 1.0?

**Comment by lukastaegert** [comment]
It is slightly different in that indeed rollup adds the banner before plugins like uglify process the generated bundle while this plugin can be placed later. Only pity that it is using the deprecated `transformBundle` hook and not the `renderChunk` hook.

**Comment by yingye** [comment]
This issue has been fixed in the new version.

**Pull request merged**
