### PR TITLE
Add copier

### PR DESCRIPTION
**Pull request by marverix**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/rollup/awesome/blob/master/.github/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Describe Your Addition

I'm adding rollup-plugin-copier which is simple plugin that copies desired files during specified phase (it's configurable). It's heavly inspired by rollup-plugin-copy (which I have mentioned in README "Thanks" section), but it seems that owner of that repo doesn't maintain it anymore and issues and fixes are just hanging in eternity. I would like to support community of rollup with my plugin.

### CODE REVIEW

**Comment by marverix** [comment]
I also understand that this repo may be not mature enough, so I have nothing against if this PR will hang for those 30 days.

**Comment by GrosSacASac** [comment]
Thanks

**Comment by shellscape** [comment]
Thanks for submitting to the list, but I think you missed the intent of the first guideline:

> If you just created something, wait at least 30 days **before submitting.**

I'm open to suggestions as to how to make that clearer since several people haven't understood that part and have submitted anyways. It's especially troubling since one of the check-tasks is to re-read the guidelines. 

Unfortunately, we have to pass on your submission and close your PR. Please submit a new PR for review after your project has reached the 30 day mark.

**Comment by marverix** [comment]
I understand and I'm ok with your decision, but IMO many projects do not mature because of lack of support from community. I find this repo a way to share something with target community (in this case _rollup community_). Problem that I find very often is that is not like people are lazy or don't want to work anymore on some project. Rather it's lacking of support of other people. I know this problem very well becasue I don't have a lot of FE-dev friends and because of that I don't have anyone that I can share and cooporate with.

If I can propose something: Remove this rule and add in the end of this document section "Fresh projects". If after 30 days certain project will not get e.g. 5 starts (or some other "maturity indicator") then it's going to be removed. This way you are not deter and discourage people to create PR here.

**Comment by shellscape** [comment]
I can see that point of view. But that misses the mark for why the repo was created, and why the [first awesome list](https://github.com/sindresorhus/awesome) was created - it's here to showcase projects that have made the cut for the community, that do things that are truly awesome for Rollup. And that takes time. Projects take time to mature and flesh out their feature set, to weed out bugs. Your project has only been on NPM for 4 hours and is already at 1.1.0. If it's following semver, that means it's gone through a 0.x phase, a breaking change set with 1.0.0, and a new feature with 1.1.0 all in the span of 5 hours since the repo was created. That's quite a bit of turnover in a short period of time. And that says that it behooves us to wait and see how it turns out. Many projects are also abandoned by their creators early after publishing, and it would be a disservice to users to share those repos as "awesome." 

If getting the repo in front of other users is your aim, take to twitter to spread the good news, write some articles/blog posts, show it being used in the REPL, approach people in the community to help share with others. Do the leg work. You'd be shocked to see just how fast the RollupJS account, the core developers, and the community will retweet about a new Rollup project.

> If I can propose something: Remove this rule and add in the end of this document section "Fresh projects". If after 30 days certain project will not get e.g. 5 starts (or some other "maturity indicator") then it's going to be removed.

That would create an unfair additional burden on the maintainers who would have to babysit several repositories to monitor them for elevation status. And there will be the inevitable debate about the number of stars, the period of time, etc etc. 

> This way you are not deter and discourage people to create PR here.

If a waiting period is truly discouraging or a deterrent to folks, I would encourage them to work on exercising (or learning how to obtain) patience. This list and repo is not a home for instant gratification, nor entitlement.

---

Unfortunately this repository isn't a new or fresh project showcase. There are plenty of other mediums out there for that. I hope that my reply, while not the one you were looking for, was at the least informative.

**Comment by marverix** [comment]
Thanks

**Comment by marverix** [comment]
@shellscape Thanks a lot for your time and effort to write this down. It seems that I didn't fully understood what for _-awesome_ repo are. I totally mixed up as you mentioned "babysitting". I will wait 30 days then and try one more time.

I don't have Twitter and I don't really like social networks. I have Facebook, but only because I need. I use it from time to time. But thanks for hint with REPL and other stuff. I will try to do more "leg work".

About my repo: Yes, it's fresh, and yes - it has 3 version tags already, but I don't really find it worrisome or weird. I know how Semver works and don't put strict rules about when one should be "1.x.x" or not. From my experience "0.x.x" is something that I'm developing and not publishing to world. If I'm sure that that someone else may also use it then I'm increasing first major part of version to 1. AFAIK they even encourage user that if it's public then it should be at least "1.0.0". So please don't judge my work only by how much commits I have made, how quickly I'm changing version etc. It's totally not an indicator. I know that there is like **a lot** of public repos, tools, plugins, etc that are in phase "0.x.x" but to be honest I give a s**t about it - it's their choice. :) 

Thanks one more time and take care!
Br,
Marek

**Pull request closed without merging**
