### PR TITLE
Add rollup-plugin-smart-asset

### PR DESCRIPTION
**Pull request by sormy**
Awesome Contribution Checklist:

- [x] I have read, and re-read the [Contributing Guidelines](https://github.com/rollup/awesome/blob/master/.github/CONTRIBUTING.md)
- [x] I have searched to ensure the suggested item doesn't exist on this list
- [x] This PR contains only one item

### Please Describe Your Addition

rollup-plugin-smart-asset plugin

### CODE REVIEW

**Comment by sormy** [comment]
Hi, any news?

**Comment by sormy** [comment]
ping

**Comment by shellscape** [comment]
Hey @sormy apologies for the late response. But thanks for the PR :beer:

I feel that your README needs some more information, and could be clearer to a reader looking at the awesome list. The term `rebase` isn't really used often in Node path manipulation, and users could easily confuse that with `git rebase` (which is what I thought it was doing initially). I had to go read the tests to get a clear understanding of what was going on. Some "before and after" results in the readme would be very helpful to users. And I would encourage you to choose something other than `rebase` for a descriptor. Perhaps "changes the base directory of an import, export, or require statement"

**Comment by sormy** [comment]
Well. CSS rebase is well known term in web dev: https://www.google.com/search?q=rebase+css+assets

Two other plugins can also do some things that this plugin can do and they have references to "rebase": 

* https://github.com/rollup/rollup-plugin-url -> "usually used to rebase the assets according to HTML files."
* https://github.com/sebastian-software/rollup-plugin-rebase -> the plugin name is saying what it is doing

This plugin is similar to "https://www.npmjs.com/package/postcss-smart-asset" that has also the same modes as this plugin, including "rebase" mode.

By the way I will update the PR and description to make description more clear.

**Pull request merged**
